variables:
  DOCKER_DRIVER: overlay2

stages:
#  - fasttest
  - build_test_deploy
#
#fasttest:
#  stage: fasttest
#  image: node:latest
#  # This folder is cached between builds
#  # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#  cache:
#    paths:
#    - node_modules/
#  script:
#   - yarn install
#   - yarn run lint
#   - yarn run flow check

build_test_deploy:
  stage: build_test_deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/cache-pip"
  cache:
    paths:
    - "$CI_PROJECT_DIR/cache-apk"
    - "$CI_PROJECT_DIR/cache-pip"
  before_script:
    - mkdir cache cache/apk cache/pip
    - ls $CI_PROJECT_DIR/cache-apk
    - ls $PIP_CACHE_DIR
    - ln -s /var/cache/apk cache/apk/
    - apk update
    - apk add py-pip yarn
    - pip install docker-compose
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - yarn run d:build
  script:
     - ls $CI_PROJECT_DIR/cache-apk
     - ls $PIP_CACHE_DIR
     - yarn run d:test
#  after_script:
#    - docker push $IMAGE_NAME
