variables:
  DOCKER_DRIVER: overlay2

stages:
  - test_whitebox

test_whitebox:
  stage: test_whitebox
  image: node:carbon
  cache:
    paths:
    - node_modules/
    - server/node_modules/
    - client/node_modules/
  before_script:
   - yarn install
   - cd ./client && yarn install
   - cd ../server && yarn install
   - cd ../
  after_script:
     - yarn run lint
  script:
   - echo 'Prion'
