variables:
  DOCKER_DRIVER: overlay2

stages:
#  - fasttest
  - build_test_deploy
#
#fasttest:
#  stage: fasttest
#  image: node:latest
#  # This folder is cached between builds
#  # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#  cache:
#    paths:
#    - node_modules/
#  script:
#   - yarn install
#   - yarn run lint
#   - yarn run flow check

build_test_deploy:
  stage: build_test_deploy
  image: ncrmro/ci-compose:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - yarn run d:build
  script:
     - yarn run d:test
#  after_script:
#    - docker push $IMAGE_NAME
