variables:
  DOCKER_DRIVER: overlay2

stages:
  - test_whitebox
  - build

variables:
  CLIENT_PORT: 8080
  SERVER_HOST: localhost
  SERVER_PORT: 8081

test_whitebox:
  stage: test_whitebox
  image: node:carbon
  cache:
    paths:
    - node_modules/
    - server/node_modules/
    - client/node_modules/
  before_script:
    - yarn run install:all
  script:
    # Running build will additionally lint the codebase.
    - yarn run build
  after_script:
    - echo 'Prion brought to you by JTCO and JTX'
    - echo 'To see more check out jtco.io and jtronics.exchange'

build:
  stage: build
  image: ncrmro/ci-compose:latest
  variables:
    SERVER_HOST: docker
  services:
      - docker:dind
  before_script:
    - yarn run dc:build
    - yarn run dc:start -d
    - sleep 3s
  script:
    - curl http://$SERVER_HOST:$CLIENT_PORT
  after_script:
    - yarn run dc down
    - echo 'Prion brought to you by JTCO and JTX'
    - echo 'To see more check out jtco.io and jtronics.exchange'
