variables:
  DOCKER_DRIVER: overlay2
  PROJECT_TITLE: Aeon
  FRONTEND_HOST: 0.0.0.0
  FRONTEND_PORT: 6080
  BACKEND_HOST: 0.0.0.0
  BACKEND_PORT: 6081
  HTTPS: "false"
  PUBLIC_PATH: /static/

stages:
  - test_whitebox
  - build

test_whitebox:
  stage: test_whitebox
  image: node:carbon
  cache:
    paths:
    - node_modules/
    - server/node_modules/
    - client/node_modules/
  before_script:
    - yarn run install:all
  script:
    # Running build will additionally lint the codebase.
    - yarn run build

build:
  stage: build
  image: ncrmro/ci-compose:latest
  variables:
    SERVER_HOST: docker
  services:
      - docker:dind
  before_script:
    - yarn run dc build
    - yarn run dc:selenium up -d backend frontend proxy firefox chrome selenium_hub
  script:
    - yarn run dc:test
  after_script:
    - yarn run dc:selenium down
    - echo 'Aeon brought to you by JTCO and JTX'
    - echo 'To see more check out jtco.io and jtronics.exchange'
