variables:
  DOCKER_DRIVER: overlay2

stages:
  - fasttest

fasttest:
  stage: fasttest
  image: node:latest

  # This folder is cached between builds
  # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
  cache:
    paths:
    - node_modules/

  script:
   - yarn install
   - yarn run lint
   - yarn run flow check

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - setup-apkcache
    - apk add --no-cache py-pip yarn
    - ls /etc/apk/cache
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --build-arg BASE_IMAGE=$SERVER_IMAGE --target build -t $IMAGE_NAME .
  after_script:
    - docker push $IMAGE_NAME
