variables:
  DOCKER_DRIVER: overlay2

stages:
  - test_whitebox

test_whitebox:
  stage: test_whitebox
  image: node:carbon
  cache:
    paths:
    - node_modules/
    - server/node_modules/
    - client/node_modules/
  before_script:
    - yarn install
    - cd ./client && yarn install
    - cd ../server && yarn install
    - cd ../
    - yarn run lint
    - yarn run build
    - yarn run prod:start:background
    - sleep 3s
  script:
    - curl http://localhost:8080
  after_script:
    - echo 'Prion brought to you by JTCO and JTX'
    - echo 'To see more check out jtco.io and jtronics.exchange'
