version: '3.4'
services:
  client-serve:
    image: ${IMAGE}
    restart: always
    ports:
        - "5000:5000"
    build:
      context: .
      target: build

  db:
    image: postgres:alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
