version: '3.4'
services:
  client-serve:
    image: ${IMAGE}
    restart: always
    ports:
        - "5000:5000"
    build:
      context: .
      target: build
      args:
          REACT_APP_GRAPHQL_URL: 192.168.99.100:4000


