version: '3.4'
services:
  frontend:
    container_name: frontend
    image: registry.gitlab.com/jtco-io/jtx/frontend
    build:
      context: ./client
    restart: always
    ports:
        - 8080:8080
    environment:
      - CLIENT_PORT=8080
      - SERVER_HOST=backend
      - SERVER_PORT=8081


  backend:
    container_name: backend
    image: registry.gitlab.com/jtco-io/jtx/backend
    build:
      context: ./server
    restart: always
    ports:
        - 8081:8081
    environment:
          - SERVER_PORT=8081

