version: '3.4'
services:
  server:
    image: ${REPO}/server
    restart: always
    ports:
    - "4000:4000"
    build:
      context: ./server
    environment:
      PRISMA_ENDPOINT: "http://prisma:4466/database/dev"
    depends_on:
    - prisma


  prisma:
    image: prismagraphql/prisma:1.7.3
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        #managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: db
            port: 5432
            user: root
            password: prisma
    depends_on:
    - db


  db:
    image: postgres:alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
